### ISSUE TITLE
[Feature Request] Add DiscordLevelingSystem.get_xp_for_level()

### ISSUE THREAD

**Issue by xFGhoul** [Defxult/discordLevelingSystem#10]
I don't know if this is possible or not but this method would return an `int` based on the amount of `xp` needed for a level

It's similar to `next_level_up()` but instead of returning the `remaining` amount it returns the `total` amount

Example:

```py
xp_needed_for_level_2 = await DiscordLevelingSystem.get_xp_for_level(2)
print(xp_needed_for_level_2)
# >>> 200 (Example int)
```

**Comment by Dinkytora** [comment]
I support this idea, would be a really good utility method

**Comment by Defxult** [comment]
Surprised I never added this. Thanks for the request! It has been added to the library.
