### ISSUE TITLE
i dont get level messages also rank command doesnt work

### ISSUE THREAD

**Issue by atkn1337** [Defxult/discordLevelingSystem#11]
hello i wrote this code 
```py
import json
import discord
from discord.ext import commands
from discordLevelingSystem import DiscordLevelingSystem, LevelUpAnnouncement, RoleAward

# get token from settings.json
with open('settings.json') as f:
    settings = json.load(f)
    token = settings['token']

embed = discord.Embed()
embed.set_author(name=LevelUpAnnouncement.Member.name, icon_url=LevelUpAnnouncement.Member.avatar_url)
embed.description = f'Congrats {LevelUpAnnouncement.Member.mention}! You are now level {LevelUpAnnouncement.LEVEL} 😎'

announcement = LevelUpAnnouncement(embed)

bot = commands.Bot(command_prefix=settings["prefix"])
lvl = DiscordLevelingSystem(rate=12, per=1, level_up_announcement=announcement)
lvl.connect_to_database_file("./level/DiscordLevelingSystem.db")


# set up leveling system
@bot.event
async def on_ready():
    print(f'{bot.user.name} has connected to Discord!')

@bot.command()
async def rank(ctx):
    data = await lvl.get_data_for(ctx.author)
    await ctx.send(f'You are level {data.level} and your rank is {data.rank}')



bot.run(token)
```
but when i start the bot it doesnt gave me levels and when i type !rank it gave me error : `discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'level'`
can you help me?

**Comment by atkn1337** [comment]
sorry if this is a bug

**Comment by Defxult** [comment]
Method `get_data_for()` is returning `None` because the member information was not found in the database. I see that you're missing the `on_message` event as well as the `award_xp()` method as displayed in the [handling XP](https://github.com/Defxult/discordLevelingSystem#handling-xp) documentation. Those are needed in order for `get_data_for()` to return a value. 

Also, please use the "Bug report" template if any other issues are reported. It helps me track down where/why an issue is occurring.

**Comment by atkn1337** [comment]
> Method `get_data_for()` is returning `None` because the member information was not found in the database. I see that you're missing the `on_message` event as well as the `award_xp()` method as displayed in the [handling XP](https://github.com/Defxult/discordLevelingSystem#handling-xp) documentation. Those are needed in order for `get_data_for()` to return a value.
> 
> Also, please use the "Bug report" template if any other issues are reported. It helps me track down where/why an issue is occurring.

after i add leveling system when i press CTRL + C it waits me a lot to close the bot can i fix this?
