### ISSUE TITLE
Add support for MongoDB

### ISSUE THREAD

**Issue by jsmsj** [Defxult/discordLevelingSystem#14]
Hi, i would like to request mongodb integration. as i want to host my py-cord bot on heroku and since heroku has ephemeral storage system, the .db files would be cleared out periodically.
Hence i request support for mongodb

**Comment by Defxult** [comment]
That would require an almost complete overhaul of the library because of the different methods compared to SQLite, and that's something I am not willing to do at the moment. Maybe some time in the future but it's unlikely.

**Comment by jsmsj** [comment]
Well anyways, thankyou for early response. 
Hoping to see mongoDB support in future.
You are awesome 😊

**Comment by duncansykes** [comment]
it's very easy to edit the code in the file levelling_system.py to add support for your own database, I managed to implement my own crud operations for PostgreSQL in about 5 hours. and it works really well.
So if you need mongoDB support, i can imagine it would be just as easy. (make a crud file that handles all database operations, and just replace the database operations with those functions)
