### ISSUE TITLE
open for contribution?

### ISSUE THREAD

**Issue by krishsharma0413** [Defxult/discordLevelingSystem#16]
Is the repository open for contribution?

If it is open I would love to work on **some** leveling cards for more user customization...

using PIL i made this and would live to implement here, if possible 

![image](https://cdn.discordapp.com/attachments/893495203304992778/993913866230714368/unknown.png)

also i have some ideas for leaderboard
I would love to work on a fork if i am allowed to make something like this!

**Comment by Defxult** [comment]
It is open for contributions. I haven't added rank cards because I don't have any experience with Pillow but rank cards would be a good addition. What do you have in mind for leaderboard?

**Comment by krishsharma0413** [comment]
the leaderboard i just finished working on and should look somewhat like this...

![image](https://user-images.githubusercontent.com/77439837/190332913-3e49b581-7814-4624-84fb-62549ae1da98.png)


Though this is subjected to change.

PS: the avatar on the LEADERBOARD is actually the server icon and background image is a little too weird

**Comment by Defxult** [comment]
Oh ok. It looks pretty cool! If you make a PR, I'll review it, test it, all the pre-release checks and whatnot. From the looks of it, it would be a great addition.

**Comment by krishsharma0413** [comment]
Alright i will make a draft PR when i get the time and we should discuss a little more things while we at it,

1) Avatar are images so we might need to use fp or requests/aiohttp for URLs.

2) Should there be a completely new file with its own class system for this or do you want me to integrate it within `DiscordLevelingSystem` class.

address these issues before i start working on the PR or later would have to redo everything if it doesn't meet your expectations

**Comment by Defxult** [comment]
aiohttp would be the better choice. As for number 2, I'd make it's own class for it.
