### ISSUE TITLE
Features Request 

### ISSUE THREAD

**Issue by DevInfinix** [Defxult/discordLevelingSystem#2]
Hello @Defxult !
I would like to suggest some features which can be added to the `PyPI / GitHub` lib version in the next update.

> **1. LevelUpAnnouncement Class Attributes: (for embeds)**

- `LevelUpAnnouncement.AUTHOR_AVATAR`

- `LevelUpAnnouncement.AUTHOR_NAME (instead of mention)`

- `LevelUpAnnouncement.GUILD_ICON` (url)

> **2. XP / LEVEL Methods**

- `DiscordLevelingSystem.add_xp(member: Member)`

- `DiscordLevelingSystem.remove_xp(member: Member)`

- `DiscordLevelingSystem.set_level(member: Member)`

- `DiscordLevelingSystem.set_booster_role(role: Role, *, boost_amount)` (eg. boost_amount : 2x, 3x, 0.5x) 

> **3. EASY LEADERBOARD Methods**

- `DiscordLevelingSystem.leaderboard(guild: Guild, message : str)` (normal message)

> **3. ADVANCED LEADERBOARD Methods**

- `DiscordLevelingSystem.leaderboard(guild: Guild, message : Embed)` (embedded message)

> **4. NEW CLASS For Leaderboard**

- **Class Attributes for** `Leaderboard` **:** (discord.Embed) 

- `Leaderboard.MEMBER_NAME`

- `Leaderboard.MEMBER_MENTION`

- `Leaderboard.GUILD_ICON` (url)

Thanks.

> (Discord : INFINIX#7276)

**Comment by Defxult** [comment]
1 and 2 would be nice additions. What I'll probably end up doing is provide access to the `discord.Member` object in `LevelUpAnnouncement` so users aren't too limited in what they'd like to use. As for 3 and 4, a leaderboard is something users have to implement themselves. The library already gives you the information needed via the `each_member_data` method. From there it should be easy to make your own whether that be in an embed or a message. I'll most likely add the `discord.Member` object to `MemberData` as well to enhance the ability to make leaderboards.

**Comment by DevInfinix** [comment]
> 1 and 2 would be nice additions. What I'll probably end up doing is provide access to the `discord.Member` object in `LevelUpAnnouncement` so users aren't too limited in what they'd like to use. As for 3 and 4, a leaderboard is something users have to implement themselves. The library already gives you the information needed via the `each_member_data` method. From there it should be easy to make your own whether that be in an embed or a message. I'll most likely add the `discord.Member` object to `MemberData` as well to enhance the ability to make leaderboards.

Okay! Thanks a lot ❤️
I'll be eagerly waiting for the update !

> Edit : Can u please provide an example using `MemberData` class in the `readme.md` file :)
